version: '3.8'
services:
  ambar-compiler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ambar-compiler
    volumes:
      - ./src:/app/src
      - ./include:/app/include
      - ./output:/app/output
      - ./compile.sh:/app/compile.sh
    working_dir: /app
    stdin_open: true
    tty: true
  
  ambar-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ambar-dev
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash
    stdin_open: true
    tty: true
